export enum DeviceType {
  CAMERA = "camera",
  COVER = "cover",
  FAN = "fan",
  GENERIC_IOT = "generic_iot",
  HEATING = "heating",
  LAWN_MOWER_ROBOT = "lawn_mower_robot",
  LIGHT = "light",
  POWER_METER = "power_meter",
  PRINTER = "printer",
  NETWORK = "network",
  SET_TOP_BOX = "set_top_box",
  SMART_DIMMER = "smart_dimmer",
  SMART_SPEAKER = "smart_speaker",
  SMART_SWITCH = "smart_switch",
  TELEVISION = "television",
  UPS = "ups",
  VACUUM_ROBOT = "vacuum_robot",
}
