export enum DeviceType {
  CAMERA = "camera",
  COVER = "cover",
  FAN = "fan",
  GENERIC_IOT = "generic_iot",
  HEATING = "heating",
  LIGHT = "light",
  POWER_METER = "power_meter",
  PRINTER = "printer",
  NETWORK = "network",
  SMART_DIMMER = "smart_dimmer",
  SMART_SPEAKER = "smart_speaker",
  SMART_SWITCH = "smart_switch",
  TELEVISION = "television",
  VACUUM_ROBOT = "vacuum_robot",
}
